[package]
name = "cooper"
version = "0.1.0"
edition = "2021"

[dependencies]
lynch = { path = "crates/lynch", version = "0.0.1-dev"}
application = { path = "crates/application", version = "0.0.1-dev"}
frost = { path = "crates/frost", version = "0.0.1-dev"}