[package]
name = "lynch"
version = "0.0.1-dev"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.20"
env_logger = "0.10.1"
frost = {path = "../frost", version = "0.0.1-dev"}
ash = {version="0.37.0", features = ["linked", "debug"]}
vk-sync = {git = "https://github.com/simplerr/vk-sync-rs"}
gltf = "0.16.0"
winapi = "0.3.6"
cgmath = "0.17.0"
image = "0.21.0"
tobj = "0.1.6"
memoffset = "0.5.1"
dolly = "0.2.0"
raw-window-handle = "0.3"
winit = "0.27"
uuid = {version = "1.6.1", features = [ "v4", "fast-rng", "macro-diagnostics",]}
glam = "0.20.2"
gpu-allocator = { version = "0.25", default-features = false, features = ["vulkan"] }
shaderc = "0.7.3"
rspirv-reflect = { git = "https://github.com/simplerr/rspirv-reflect.git" } # "0.6.0"
libloading = "0.8"
phf = { version = "0.11.2", features = ["macros"] }
imgui = "0.11.0"
imgui-rs-vulkan-renderer = { version = "1.12.0" , features = ["gpu-allocator", "dynamic-rendering"] }
imgui-winit-support = "^0.11"