[package]
name = "application"
version = "0.0.1-dev"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lynch = { path = "../lynch", version = "0.0.1-dev"}
winit = "0.29.2"